from langchain_core.prompts import ChatPromptTemplate
from src.config import llm
from src.state import AgentState, ArchitectureSchema

def architect_agent(state: AgentState):
    print("--- NODE: ARCHITECT ---")
    
    template_name = state.get("template_name", "react_ts_tailwind")

    prompt = ChatPromptTemplate.from_messages([
        ("system", (
            "You are a Senior Software Architect. Create a JSON blueprint of the files and configuration needed.\n"
            "The project uses a 'react_ts_tailwind' base template which already handles:\n"
            "- Vite, TypeScript, and Tailwind configuration.\n"
            "- A dynamic main entry (main.tsx) and layout (App.tsx).\n"
            "- A dynamic Home page (src/pages/Home.tsx) that renders sections from 'src/components/sections/'.\n\n"
            
            "AVAILABLE PRE-BUILT SECTIONS (Reuse these instead of recreating if they fit the task):\n"
            "- 'Hero': Premium intro with title, subtitle, and CTA.\n"
            "- 'Features': 6-item grid with icons and descriptions.\n"
            "- 'CTA': High-contrast conversion banner.\n\n"
            
            "YOUR TASK:\n"
            "1. Define the 'template_context' (JSON object):\n"
            "   - 'project_name': String\n"
            "   - 'primary_color': Hex code (standard: #3b82f6)\n"
            "   - 'secondary_color': Hex code (standard: #10b981)\n"
            "   - 'custom_components': A list of objects like {{'component_name': 'Hero'}}. These will be rendered in order on the Home page.\n"
            "2. List additional 'files' (e.g., custom hooks, utils, or new components NOT in the pre-built library).\n"
            "   - CRITICAL: DO NOT list 'Hero.tsx', 'Features.tsx', or 'CTA.tsx' in this 'files' list if you are using the pre-built versions. They already exist in 'src/components/sections/'.\n"
            "   - DO NOT list 'App.tsx' or 'main.tsx' unless you are performing a complete structural overhaul. The template versions already handle dynamic rendering.\n"
            "   - Only add a section file here if you are creating a completely new, custom section (e.g., 'src/components/sections/Testimonials.tsx').\n"
            "3. Provide a 'logic_summary' of your architectural decisions."
        )),
        ("user", "User Request: {input}")
    ])
    
    chain = prompt | llm.with_structured_output(ArchitectureSchema)
    result = chain.invoke({"input": state["user_prompt"]})
    
    # Use the context generated by the LLM
    final_context = result.template_context
    
    return {
        "architecture": result.model_dump(),
        "template_name": template_name,
        "template_context": final_context,
        "revision_count": 0
    }
