from langchain_core.prompts import ChatPromptTemplate
from src.config import llm, PROTECTED_FILES
from src.state import AgentState, ArchitectureSchema

def architect_agent(state: AgentState):
    print("--- NODE: ARCHITECT ---")
    
    template_name = state.get("template_name", "react_ts_tailwind")

    prompt = ChatPromptTemplate.from_messages([
        ("system", (
            "You are a Senior Software Architect. Create a JSON blueprint of the files and configuration needed.\n"
            "The project uses a 'react_ts_tailwind' base template which already handles:\n"
            "- Vite, TypeScript, and Tailwind configuration.\n"
            "- A dynamic main entry (main.tsx) and layout (App.tsx).\n"
            "- A dynamic Home page (src/pages/Home.tsx) that renders sections from 'src/components/sections/'.\n\n"
            
            "AVAILABLE PRE-BUILT SECTIONS (Reuse these instead of recreating if they fit the task):\n"
            "- 'Hero': Premium intro with title, subtitle, and CTA.\n"
            "- 'Features': 6-item grid with icons and descriptions.\n"
            "- 'CTA': High-contrast conversion banner.\n\n"
            
            "YOUR TASK:\n"
            "1. Define the 'template_context' (JSON object):\n"
            "   - 'project_name': String\n"
            "   - 'primary_color': Hex code (standard: #3b82f6)\n"
            "   - 'secondary_color': Hex code (standard: #10b981)\n"
            "   - 'features': (Optional) Global list of features to be used across sections. Each feature should have 'title' and 'description'.\n"
            "   - 'custom_components': A list of objects like {{'component_name': 'Hero'}}. These will be rendered in order on the Home page.\n"
            "2. List 'files' to be generated/implemented.\n"
            "   - For every component listed in 'custom_components', you MUST list its file path (e.g., 'src/components/sections/Hero.tsx').\n"
            "   - The project uses structured components with specific AI markers (IMPORTS, INTERFACE, STATE, HOOKS, JSX). Your plan should accommodate these.\n"
            "3. Provide a 'logic_summary'. This is CRITICAL. \n"
            "   - For each section, specify the intended logic (e.g., 'Hero section should use a framer-motion slide-in effect', 'Features should map over the features prop into high-quality cards').\n"
            "   - This summary will guide the Implementor on how to fill the markers correctly."
        )),
        ("user", "User Request: {input}")
    ])
    
    chain = prompt | llm.with_structured_output(ArchitectureSchema)
    result = chain.invoke({"input": state["user_prompt"]})
    
    # Use the context generated by the LLM
    final_context = result.template_context
    
    # These files are part of the base template and should not be modified by the AI
    # unless a total structural overhaul is intended (which is rare).

    arch_data = result.model_dump()
    original_files = arch_data.get("files", [])
    
    # Only keep files that are NOT in the protected list
    sanitized_files = [f for f in original_files if f not in PROTECTED_FILES]

    if len(sanitized_files) < len(original_files):
        removed = set(original_files) - set(sanitized_files)
        print(f"🛡️  Filter Active: Removed protected files from plan: {list(removed)}")
        arch_data["files"] = sanitized_files
    
    from src.utils.jinja_renderer import render_template_folder
    rendered = {}
    try:
        rendered = render_template_folder(template_name, final_context)
    except Exception as e:
        print(f"⚠️ Initial template rendering failed: {e}")

    return {
        "architecture": arch_data,
        "template_name": template_name,
        "template_context": final_context,
        "rendered_templates": rendered,
        "revision_count": 0
    }
